api_platform:
  title: E-commerce API
  version: 1.0.0
  # Good cache defaults for REST APIs
  defaults:
    stateless: true
    cache_headers:
      vary: ['Content-Type', 'Authorization', 'Origin']
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header